set(XSWL_YOUDIDIT_DEPS_MODE "auto" CACHE STRING "Dependency source mode: auto, system, vendor")
set_property(CACHE XSWL_YOUDIDIT_DEPS_MODE PROPERTY STRINGS auto system vendor)

if(NOT XSWL_YOUDIDIT_DEPS_MODE STREQUAL "auto" AND
   NOT XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system" AND
   NOT XSWL_YOUDIDIT_DEPS_MODE STREQUAL "vendor")
    message(FATAL_ERROR "Invalid XSWL_YOUDIDIT_DEPS_MODE='${XSWL_YOUDIDIT_DEPS_MODE}'. Allowed values: auto, system, vendor")
endif()

set(XSWL_YOUDIDIT_TL_OPTIONAL_TARGET "" CACHE STRING "Existing target name that provides tl::optional headers")
set(XSWL_YOUDIDIT_TL_EXPECTED_TARGET "" CACHE STRING "Existing target name that provides tl::expected headers")
set(XSWL_YOUDIDIT_SIGNALS_TARGET "" CACHE STRING "Existing target name that provides xswl/signals.hpp")

set(XSWL_YOUDIDIT_TL_OPTIONAL_INCLUDE_DIR "" CACHE PATH "System include dir containing tl/optional.hpp")
set(XSWL_YOUDIDIT_TL_EXPECTED_INCLUDE_DIR "" CACHE PATH "System include dir containing tl/expected.hpp")
set(XSWL_YOUDIDIT_SIGNALS_INCLUDE_DIR "" CACHE PATH "System include dir containing xswl/signals.hpp")
set(XSWL_YOUDIDIT_NLOHMANN_INCLUDE_DIR "" CACHE PATH "System include dir containing nlohmann/json.hpp")
set(XSWL_YOUDIDIT_HTTPLIB_INCLUDE_DIR "" CACHE PATH "System include dir containing httplib.h")

add_library(xswl_youdidit_deps INTERFACE)

set(_xswl_vendor_tl_optional FALSE)
set(_xswl_vendor_tl_expected FALSE)
set(_xswl_vendor_signals FALSE)
set(_xswl_vendor_nlohmann FALSE)
set(_xswl_vendor_httplib FALSE)

function(_xswl_require_include_dir _name _path)
    if(NOT _path OR NOT EXISTS "${_path}")
        message(FATAL_ERROR "${_name} include dir is not set or does not exist: '${_path}'")
    endif()
endfunction()

function(_xswl_try_use_target _target_var _target_name _fallback_var)
    if(${_target_var} AND TARGET "${${_target_var}}")
        target_link_libraries(xswl_youdidit_deps INTERFACE "${${_target_var}}")
        set(${_fallback_var} FALSE PARENT_SCOPE)
    elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system" AND ${_target_var})
        message(FATAL_ERROR "Configured target '${${_target_var}}' for ${_target_name} was not found")
    else()
        set(${_fallback_var} TRUE PARENT_SCOPE)
    endif()
endfunction()

if(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "vendor")
    set(_xswl_vendor_tl_optional TRUE)
    set(_xswl_vendor_tl_expected TRUE)
    set(_xswl_vendor_signals TRUE)
    set(_xswl_vendor_nlohmann TRUE)
    set(_xswl_vendor_httplib TRUE)
else()
    _xswl_try_use_target(XSWL_YOUDIDIT_TL_OPTIONAL_TARGET tl_optional _xswl_vendor_tl_optional)
    _xswl_try_use_target(XSWL_YOUDIDIT_TL_EXPECTED_TARGET tl_expected _xswl_vendor_tl_expected)
    _xswl_try_use_target(XSWL_YOUDIDIT_SIGNALS_TARGET xswl_signals _xswl_vendor_signals)

    if(_xswl_vendor_tl_optional)
        if(XSWL_YOUDIDIT_TL_OPTIONAL_INCLUDE_DIR)
            _xswl_require_include_dir("tl_optional" "${XSWL_YOUDIDIT_TL_OPTIONAL_INCLUDE_DIR}")
            target_include_directories(xswl_youdidit_deps INTERFACE "${XSWL_YOUDIDIT_TL_OPTIONAL_INCLUDE_DIR}")
            set(_xswl_vendor_tl_optional FALSE)
        elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system")
            message(FATAL_ERROR "System mode missing tl::optional. Set XSWL_YOUDIDIT_TL_OPTIONAL_INCLUDE_DIR or XSWL_YOUDIDIT_TL_OPTIONAL_TARGET")
        endif()
    endif()

    if(_xswl_vendor_tl_expected)
        if(XSWL_YOUDIDIT_TL_EXPECTED_INCLUDE_DIR)
            _xswl_require_include_dir("tl_expected" "${XSWL_YOUDIDIT_TL_EXPECTED_INCLUDE_DIR}")
            target_include_directories(xswl_youdidit_deps INTERFACE "${XSWL_YOUDIDIT_TL_EXPECTED_INCLUDE_DIR}")
            set(_xswl_vendor_tl_expected FALSE)
        elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system")
            message(FATAL_ERROR "System mode missing tl::expected. Set XSWL_YOUDIDIT_TL_EXPECTED_INCLUDE_DIR or XSWL_YOUDIDIT_TL_EXPECTED_TARGET")
        endif()
    endif()

    if(_xswl_vendor_signals)
        if(XSWL_YOUDIDIT_SIGNALS_INCLUDE_DIR)
            _xswl_require_include_dir("xswl_signals" "${XSWL_YOUDIDIT_SIGNALS_INCLUDE_DIR}")
            target_include_directories(xswl_youdidit_deps INTERFACE "${XSWL_YOUDIDIT_SIGNALS_INCLUDE_DIR}")
            set(_xswl_vendor_signals FALSE)
        elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system")
            message(FATAL_ERROR "System mode missing xswl_signals. Set XSWL_YOUDIDIT_SIGNALS_INCLUDE_DIR or XSWL_YOUDIDIT_SIGNALS_TARGET")
        endif()
    endif()

    if(XSWL_YOUDIDIT_NLOHMANN_INCLUDE_DIR)
        _xswl_require_include_dir("nlohmann" "${XSWL_YOUDIDIT_NLOHMANN_INCLUDE_DIR}")
        target_include_directories(xswl_youdidit_deps INTERFACE "${XSWL_YOUDIDIT_NLOHMANN_INCLUDE_DIR}")
    elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system")
        message(FATAL_ERROR "System mode missing nlohmann/json.hpp include dir. Set XSWL_YOUDIDIT_NLOHMANN_INCLUDE_DIR")
    else()
        set(_xswl_vendor_nlohmann TRUE)
    endif()

    if(XSWL_YOUDIDIT_HTTPLIB_INCLUDE_DIR)
        _xswl_require_include_dir("httplib" "${XSWL_YOUDIDIT_HTTPLIB_INCLUDE_DIR}")
        target_include_directories(xswl_youdidit_deps INTERFACE "${XSWL_YOUDIDIT_HTTPLIB_INCLUDE_DIR}")
    elseif(XSWL_YOUDIDIT_DEPS_MODE STREQUAL "system")
        message(FATAL_ERROR "System mode missing httplib.h include dir. Set XSWL_YOUDIDIT_HTTPLIB_INCLUDE_DIR")
    else()
        set(_xswl_vendor_httplib TRUE)
    endif()
endif()

if(_xswl_vendor_tl_optional)
    target_include_directories(xswl_youdidit_deps INTERFACE "${CMAKE_SOURCE_DIR}/third_party/tl_optional/include")
endif()

if(_xswl_vendor_tl_expected)
    target_include_directories(xswl_youdidit_deps INTERFACE "${CMAKE_SOURCE_DIR}/third_party/tl_expected/include")
endif()

if(_xswl_vendor_signals)
    target_include_directories(xswl_youdidit_deps INTERFACE "${CMAKE_SOURCE_DIR}/third_party/xswl_signals/include")
endif()

if(_xswl_vendor_nlohmann)
    target_include_directories(xswl_youdidit_deps INTERFACE "${CMAKE_SOURCE_DIR}/third_party")
endif()

if(_xswl_vendor_httplib)
    target_include_directories(xswl_youdidit_deps INTERFACE "${CMAKE_SOURCE_DIR}/third_party")
endif()

set(XSWL_YOUDIDIT_USE_VENDORED_TL_OPTIONAL ${_xswl_vendor_tl_optional} CACHE INTERNAL "Using vendored tl_optional" FORCE)
set(XSWL_YOUDIDIT_USE_VENDORED_TL_EXPECTED ${_xswl_vendor_tl_expected} CACHE INTERNAL "Using vendored tl_expected" FORCE)
set(XSWL_YOUDIDIT_USE_VENDORED_SIGNALS ${_xswl_vendor_signals} CACHE INTERNAL "Using vendored xswl_signals" FORCE)

message(STATUS "xswl-youdidit deps mode: ${XSWL_YOUDIDIT_DEPS_MODE}")
message(STATUS "  tl_optional: ${XSWL_YOUDIDIT_USE_VENDORED_TL_OPTIONAL}")
message(STATUS "  tl_expected: ${XSWL_YOUDIDIT_USE_VENDORED_TL_EXPECTED}")
message(STATUS "  xswl_signals: ${XSWL_YOUDIDIT_USE_VENDORED_SIGNALS}")